# Generated by Django 4.2.5 on 2023-09-23 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voice_record", models.FileField(upload_to="records")),
            ],
            options={"verbose_name": "Record", "verbose_name_plural": "Records",},
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("transcription", models.CharField(max_length=200)),
                ("translation", models.CharField(max_length=200)),
                ("source_language_code", models.CharField(max_length=10)),
                ("target_language_code", models.CharField(max_length=10)),
            ],
        ),
    ]
