# Generated by Django 4.2.5 on 2023-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
